# Generated by Django 5.2.17 on 2026-10-05 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nombre')),
                ('kind', models.CharField(choices=[('servicio', 'Servicio'), ('beneficio', 'Beneficio'), ('plan', 'Plan'), ('funcionalidad', 'Funcionalidad'), ('promocion', 'Promoción')], max_length=20, verbose_name='tipo')),
                ('description', models.TextField(verbose_name='descripción')),
                ('highlight', models.CharField(blank=True, help_text='Ej: Gratis desde S/ 199', max_length=120, verbose_name='dato clave')),
                ('icon', models.CharField(blank=True, default='✨', max_length=4)),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'servicio / beneficio',
                'verbose_name_plural': 'servicios y beneficios',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(verbose_name='descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='precio (S/)')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='precio anterior (S/)')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sizes', models.CharField(blank=True, help_text='Ej: S, M, L, XL', max_length=80, verbose_name='tallas / variantes')),
                ('image_url', models.URLField(blank=True, verbose_name='imagen (URL)')),
                ('emoji', models.CharField(blank=True, default='🛍️', max_length=4)),
                ('is_featured', models.BooleanField(default=False, verbose_name='destacado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['category__name', 'name'],
            },
        ),
    ]
